package com.emergencyescape.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String user;
    /** Not-null value. */
    private String psw;
    private String partenza;
    private String destinazione;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String user, String psw, String partenza, String destinazione) {
        this.id = id;
        this.user = user;
        this.psw = psw;
        this.partenza = partenza;
        this.destinazione = destinazione;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUser() {
        return user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser(String user) {
        this.user = user;
    }

    /** Not-null value. */
    public String getPsw() {
        return psw;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPsw(String psw) {
        this.psw = psw;
    }

    public String getPartenza() {
        return partenza;
    }

    public void setPartenza(String partenza) {
        this.partenza = partenza;
    }

    public String getDestinazione() {
        return destinazione;
    }

    public void setDestinazione(String destinazione) {
        this.destinazione = destinazione;
    }

}
